name: ✨ Feature Request
description: 💡 Suggest enhancements for Halo PC (SAPP/Phasor).
title: '[FEATURE] <title>'
labels: [ 'Feature', 'Needs Review' ]
assignees: 'Chalwk77'
body:
  - type: markdown
    attributes:
      value: |
        **📋 Feature Request Submission**
        > Thank you for your interest in enhancing Halo PC (SAPP/Phasor). Please provide a clear and detailed description of your feature request. Your input is invaluable to improving the experience for all players.
        
        ---
  - type: checkboxes
    id: game-type
    attributes:
      label: 🎮 Target Game
      description: "Select the applicable game(s) for your feature request."
      options:
        - label: Halo PC (retail)
        - label: Halo Custom Edition (CE)
        - label: Both (cross-compatibility)
  - type: checkboxes
    id: server-extension
    attributes:
      label: 🛠️ Server Extension
      description: "Indicate the server extension you are utilizing."
      options:
        - label: SAPP (9.8.1)
        - label: SAPP (10.0)
        - label: SAPP (10.1)
        - label: SAPP (10.2.1 - LATEST)
        - label: SAPP (Earlier version)
        - label: SAPP (Unsure)
        - label: PHASOR (2.0 - LATEST)
        - label: PHASOR (10059)
        - label: PHASOR (10058)
        - label: PHASOR (10057)
        - label: PHASOR (Unsure)
#  - type: checkboxes
#    id: custom-map
#    attributes:
#      label: 🗺️ Custom Map Usage
#      description: "Will the script be executed on a custom (non-stock) map?"
#      options:
#        - label: Yes
#        - label: No
#        - label: Unsure
  - type: checkboxes
    id: gametype-specific
    attributes:
      label: 🎯 Gametype Specificity
      description: "Does your feature request require map or gametype specificity?"
      options:
        - label: Yes
        - label: No
        - label: Unsure
  - type: textarea
    id: feature-description
    attributes:
      label: 📝 Feature Details
      description: "Provide a comprehensive description of your feature request. Include any relevant use cases or examples."
    validations:
      required: true
