name: ✨ Feature Request
description: 💡 Suggest enhancements for Halo PC (SAPP/Phasor).
title: '[FEATURE] <title>'
labels: [ 'Feature', 'Needs Review' ]
assignees:
  - Chalwk77
body:
  - type: markdown
    attributes:
      value: |
        **📋 Feature Request Submission**
        > Thank you for your interest in enhancing Halo PC (SAPP/Phasor). Please provide a clear and detailed description of your feature request. Your input is invaluable to improving the experience for all players.
        
        ---

  - type: checkboxes
    id: game-type
    attributes:
      label: 🎮 Target Game
      description: "Select the applicable game(s) for your feature request."
      options:
        - label: Halo PC (retail)
        - label: Halo Custom Edition (CE)
        - label: Both (cross-compatibility)

  - type: checkboxes
    id: server-extension
    attributes:
      label: 🛠️ Server Extension
      description: "Indicate the server extension you are utilizing."
      options:
        - label: SAPP
        - label: PHASOR

  - type: checkboxes
    id: custom-map
    attributes:
      label: 🗺️ Custom Map Usage
      description: "Will the script be executed on a custom (non-stock) map?"
      options:
        - label: Yes 👍
        - label: No ❌
        - label: Unsure ❓

  - type: checkboxes
    id: gametype-specific
    attributes:
      label: 🎯 Gametype Specificity
      description: "Does your feature request require map or gametype specificity?"
      options:
        - label: Yes 👍
        - label: No ❌
        - label: Unsure ❓

  - type: textarea
    id: feature-description
    attributes:
      label: 📝 Feature Details
      description: "Provide a comprehensive description of your feature request. Include any relevant use cases or examples."
      placeholder: "Write your feature description here..."
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: 📈 Potential Impact
      description: "Describe how this feature could enhance the gameplay experience or server performance."
      placeholder: "Explain the potential impact..."
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: 🗒️ Additional Notes
      description: "Any other information that might be relevant to your feature request."
      placeholder: "Include any other notes here..."
    validations:
      required: false
