name: Greetings

on:
  pull_request:
    types: [opened]  # Optional: Trigger only on opened pull requests
  issues:
    types: [opened]  # Optional: Trigger only on opened issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for submitting a ticket. I will respond within 2 business days of submission. Stay tuned.'
          pr-message: 'Thanks for submitting a ticket. I will respond within 2 business days of submission. Stay tuned.'
